config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :instructor_profiles
  resources :students
  resources :user_profiles
  devise_for :instructors, path: "instructors", controllers: { sessions: "instructors/sessions", confirmations: "instructors/confirmations", passwords: "instructors/passwords", registrations: "instructors/registrations", unlocks: "instructors/unlocks"}
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", unlocks: "users/unlocks"}
  root 'home#page'
  patch '/timeslot/available', to: 'timeslot#mark_available', as: 'mark_available'
  patch '/timeslot/unavailable', to: 'timeslot#mark_unavailable', as: 'mark_unavailable'
  get '/timeslot/show', to: 'timeslot#show', as: 'show_timeslot'
  get '/view_instructors', to: 'view_instructor#all', as: 'view_instructors'
end

app/models/instructor_profile.rb
class InstructorProfile < ApplicationRecord
    belongs_to :instructor
    has_one_attached :profile_picture
    before_create :init_params
    after_create :init_instructor_timeslots


    def init_params
      @params = Instructor.order(created_at: :desc).first.id
    end

    def init_instructor_timeslots
      @times = Daytime.all
      @times.each do |time|
          Timeslot.create!(available: false, booked: false, instructor_id: @params, daytime_id: time.id)
      end
    end
end

app/controllers/instructor_profiles_controller.rb
class InstructorProfilesController < ApplicationController
  before_action :authenticate_instructor!
  before_action :set_instructor_profile, only: %i[ show edit update destroy ]

  # GET /instructor_profiles or /instructor_profiles.json
  def index
    @instructor_profiles = InstructorProfile.all
  end

  # GET /instructor_profiles/1 or /instructor_profiles/1.json
  def show
    @timeslots = Timeslot.where(instructor_id: current_instructor.id)
    @daytime = Daytime.all
    @students = Student.all
    @parents = UserProfile.all
    @current_bookings = Booking.where(instructor_id: current_instructor.id)
    
    
  end

  # GET /instructor_profiles/new
  def new
    @instructor_profile = InstructorProfile.new
  end

  # GET /instructor_profiles/1/edit
  def edit
  end

  # POST /instructor_profiles or /instructor_profiles.json
  def create
    @instructor_profile = InstructorProfile.new(instructor_profile_params)
    @instructor_profile.instructor_id = current_instructor.id
    respond_to do |format|
      if @instructor_profile.save
        format.html { redirect_to @instructor_profile, notice: "Instructor profile was successfully created." }
        format.json { render :show, status: :created, location: @instructor_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instructor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructor_profiles/1 or /instructor_profiles/1.json
  def update
    respond_to do |format|
      if @instructor_profile.update(instructor_profile_params)
        format.html { redirect_to @instructor_profile, notice: "Instructor profile was successfully updated." }
        format.json { render :show, status: :ok, location: @instructor_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instructor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructor_profiles/1 or /instructor_profiles/1.json
  def destroy
    @instructor_profile.destroy
    respond_to do |format|
      format.html { redirect_to instructor_profiles_url, notice: "Instructor profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor_profile
      @instructor_profile = current_instructor.instructor_profile
    end

    # Only allow a list of trusted parameters through.
    def instructor_profile_params
      params.require(:instructor_profile).permit(:firstname, :lastname, :phone, :address, :rate, :instructor_id, :profile_picture)
    end
end

app/helpers/instructor_profiles_helper.rb
module InstructorProfilesHelper
end

app/views/instructor_profiles/_form.html.erb
<%= simple_form_for(@instructor_profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :firstname, :label => "First Name" %>
    <%= f.input :lastname, :label => "Last Name" %>
    <p> Upload a Profile Picture </p>
    <%= f.file_field :profile_picture%>
    <hr class="my-4">
    <%= f.input :phone, :label => "Phone Number (+61)"%>
    <%= f.input :address, :label => "Street Address"%>
    <%= f.input :rate, :label => "Round Hourly Rate in AUD (eg. 35)"%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/instructor_profiles/edit.html.erb
<h1>Editing Instructor Profile</h1>

<%= render 'form', instructor_profile: @instructor_profile %>

app/views/instructor_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructor Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructor_profiles.each do |instructor_profile| %>
      <tr>
        <td><%= instructor_profile.firstname %></td>
        <td><%= instructor_profile.lastname %></td>
        <td><%= instructor_profile.phone %></td>
        <td><%= instructor_profile.address %></td>
        <td><%= instructor_profile.rate %></td>
        <td><%= link_to 'Show', instructor_profile %></td>
        <td><%= link_to 'Edit', edit_instructor_profile_path(instructor_profile) %></td>
        <td><%= link_to 'Destroy', instructor_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor Profile', new_instructor_profile_path %>

app/views/instructor_profiles/new.html.erb
<h1>New Instructor Profile</h1>

<%= render 'form', instructor_profile: @instructor_profile %>

<%= link_to 'Back', instructor_profiles_path %>

app/views/instructor_profiles/show.html.erb
<hr class="my-2">
<p class="h1 text-center bg-light w-50 mx-auto rounded">Instructor Dashboard</p>
<hr class="my-2">
<div class="bg-light p-4 border rounded w-auto mx-5 mt-2 mb-3">
<div class="row justify-content-center">
    <div class="col-4 border rounded">
      <p class=" h4 text-center mt-4">Profile</p>
      <hr class="my-4">
      <% if @instructor_profile.profile_picture.attached? %>
        <%= image_tag @instructor_profile.profile_picture, class: "pro-pic center"%>
      <% else %>
        <%= image_tag "defaultpp.png", class: "pro-pic"%>
      <% end%>
      <hr class="my-4">
      <p>
        <strong>Name: </strong>
        <%= "#{@instructor_profile.firstname} #{@instructor_profile.lastname}" %>
      </p>

      <p>
        <strong>Email: </strong>
        <%= @instructor_profile.instructor.email %>
      </p>

      <p>
        <strong>Phone: </strong>
        (+61)<%= @instructor_profile.phone %>
      </p>

      <p>
        <strong>Address: </strong>
        <%= @instructor_profile.address %>
      </p>

      <p>
        <strong>Rate:</strong>
        $<%= @instructor_profile.rate %>
      </p>

      <%= link_to 'Edit Profile', edit_instructor_profile_path(@instructor_profile), class: "btn btn-primary mb-3" %>
      <%= link_to 'Configure Time Slots', '#timeconfig', class: "btn btn-primary mb-3 ml-3" %>
    </div>
    <div class="col-4 border-right">
      <p class=" h4 text-center mt-4">Upcoming Bookings</p>
      <hr class="my-4">
      <% @current_bookings.order(:date).each do |booking| %>
      <% if booking.date >= Date.today%>
      <strong><%= booking.date.strftime('%A')%> <%= @daytime.find(@timeslots.find(booking.timeslot_id).daytime_id).time%> -</strong> <%= booking.date.strftime("%m/%d/%Y")%>
      <hr class="my-1">
      <strong>Parent: </strong><%= @parents.where(user_id: booking.user_id).first.firstname %> <%= @parents.where(user_id: booking.user_id).first.lastname %>
      <br>
      <strong>Student: </strong><%= @students.find(booking.student_id).firstname %> <%= @students.find(booking.student_id).lastname %>
      <br>
      <strong>Address:</strong>
      <br>
      <%=@parents.where(user_id: booking.user_id).first.address %>
      <hr class="my-3">
      <%end%>
      <%end%>
      
    </div>
    <div class="col-4 rounded">
      <p class=" h4 text-center mt-4">Previous Bookings</p>
      <hr class="my-4">
      <% @current_bookings.order(:date).each do |booking| %>
      <% if booking.date < Date.today%>
      <strong><%= booking.date.strftime('%A')%> <%= @daytime.find(@timeslots.find(booking.timeslot_id).daytime_id).time%> -</strong> <%= booking.date.strftime("%m/%d/%Y")%>
      <hr class="my-1">
      <strong>Parent: </strong><%= @parents.where(user_id: booking.user_id).first.firstname %> <%= @parents.where(user_id: booking.user_id).first.lastname %>
      <br>
      <strong>Student: </strong><%= @students.find(booking.student_id).firstname %> <%= @students.find(booking.student_id).lastname %>
      <br>
      <strong>Address:</strong>
      <br>
      <%=@parents.where(user_id: booking.user_id).first.address %>
      <hr class="my-3">
      <%end%>
      <%end%>
      
    </div>
  </div>
</div>
<p id="timeconfig" class="h1 text-center mb-3 bg-light w-50 mx-auto border rounded">Configure Available Time Slots</p>
<div class="d-flex flex-wrap bg-light p-4 border rounded w-auto mx-5 mt-2 mb-3">
<% @timeslots.order(:id).each do |timeslot| %>
  <div class="border rounded m-1 p-2">
  <p class = "m-0">
  <strong><%= @daytime.find("#{timeslot.daytime_id}").weekday %></strong>:
  <%= @daytime.find("#{timeslot.daytime_id}").time %>
  </p>
  <% if timeslot.booked %>
  <p class="text-danger m-0">Booked</p>
  <%end%>
  <% if timeslot.available %>
  <p class="text-success m-0">Available</p>
  <%= button_to "Make Unavailable", mark_unavailable_path, class: "btn btn-secondary", params: {timeslot_id: timeslot.id}, method: :patch%>
  <%else%>
  <p class="text-danger m-0">Unavailable</p>
  <%= button_to "Make Available", mark_available_path, class: "btn btn-primary", params: {timeslot_id: timeslot.id}, method: :patch%>
  <%end%>
  </div>
  
<%end%>
</div>