config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :instructor_profiles
  resources :students
  resources :user_profiles
  devise_for :instructors, path: "instructors", controllers: { sessions: "instructors/sessions", confirmations: "instructors/confirmations", passwords: "instructors/passwords", registrations: "instructors/registrations", unlocks: "instructors/unlocks"}
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", unlocks: "users/unlocks"}
  root 'home#page'
  patch '/timeslot/available', to: 'timeslot#mark_available', as: 'mark_available'
  patch '/timeslot/unavailable', to: 'timeslot#mark_unavailable', as: 'mark_unavailable'
  get '/timeslot/show', to: 'timeslot#show', as: 'show_timeslot'
  get '/view_instructors', to: 'view_instructor#all', as: 'view_instructors'
end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">SwimSage</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <%if user_signed_in? || instructor_signed_in?%>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Dashboard</a>
          </li>
        </ul>
        <%end%>
      </div>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <span class="navbar-text px-3">
              <%= current_user.email %>
              </span>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
            </li>
          <% elsif instructor_signed_in? %>
            <li class="nav-item">
              <span class="navbar-text px-3">
              <%= current_instructor.email %>
              </span>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_instructor_session_path, method: :delete, class: "btn btn-outline-secondary" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Parent Sign In", new_user_session_path, method: :get, class: "btn btn-primary" %>
            </li>
            <li class="nav-item m-2">
            </li>
            <li class="nav-item">
              <%= link_to "Instructor Sign In", new_instructor_session_path, method: :get, class: "btn btn-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>