config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :instructor_profiles
  resources :students
  resources :user_profiles
  devise_for :instructors, path: "instructors", controllers: { sessions: "instructors/sessions", confirmations: "instructors/confirmations", passwords: "instructors/passwords", registrations: "instructors/registrations", unlocks: "instructors/unlocks"}
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", unlocks: "users/unlocks"}
  root 'home#page'
  patch '/timeslot/available', to: 'timeslot#mark_available', as: 'mark_available'
  patch '/timeslot/unavailable', to: 'timeslot#mark_unavailable', as: 'mark_unavailable'
  get '/timeslot/show', to: 'timeslot#show', as: 'show_timeslot'
  get '/view_instructors', to: 'view_instructor#all', as: 'view_instructors'
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_picture
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_profile, only: %i[ show edit update destroy ]

  # GET /user_profiles or /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1 or /user_profiles/1.json
  def show
    @students = Student.where(user_id: current_user.id)
    @bookings = Booking.all.order(:date)
    @timeslots = Timeslot.all
    @daytime = Daytime.all
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles or /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.user_id = current_user.id
    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: "User profile was successfully created." }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1 or /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: "User profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1 or /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: "User profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = current_user.user_profile
    end
    

    # Only allow a list of trusted parameters through.
    def user_profile_params
      params.require(:user_profile).permit(:firstname, :lastname, :phone, :address, :user_id, :profile_picture)
    end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= simple_form_for(@user_profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :firstname, :label => "First Name" %>
    <%= f.input :lastname, :label => "Last Name" %>
    <p> Upload a Profile Picture </p>
    <%= f.file_field :profile_picture%>
    <hr class="my-4">
    <%= f.input :phone, :label => "Phone Number (+61)"%>
    <%= f.input :address, :label => "Street Address"%>
  </div>
<hr class="my-2">
  <div class="form-actions">
    <%= f.submit "Update Profile", class: "btn btn-primary mr-3" %>
    <%= link_to 'Back to Profile', @user_profile, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<hr class="my-2">
<p class="h1 text-center bg-light w-50 mx-auto rounded">Edit Profile</p>
<hr class="mt-2 mb-4">
<div class="bg-light p-4 border rounded w-auto mx-5 mt-2 mb-2">

<%= render 'form', user_profile: @user_profile %>

</div>

app/views/user_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.firstname %></td>
        <td><%= user_profile.lastname %></td>
        <td><%= user_profile.phone %></td>
        <td><%= user_profile.address %></td>
        <td><%= user_profile.user_id %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New User Profile</h1>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<hr class="my-2">
<p class="h1 text-center bg-light w-50 mx-auto rounded">Parent Dashboard</p>
<hr class="my-2">
<div class="bg-light p-4 border rounded w-auto mx-5 mt-3 mb-3">
  <div class="row justify-content-around">
      <div class="col-4 border rounded h-50">
        <p class=" h4 text-center mt-4">Profile</p>
        <hr class="my-4">
        <% if @user_profile.profile_picture.attached? %>
          <%= image_tag @user_profile.profile_picture, class: "pro-pic"%>
        <% else %>
          <%= image_tag "defaultpp.png", class: "pro-pic"%>
        <% end%>
        <hr class="my-4">
        <p>
          <strong><%= "#{@user_profile.firstname} #{@user_profile.lastname}" %></strong>
        </p>

        <p>
          <strong>Email: </strong>
          <%= @user_profile.user.email %>
        </p>

        <p>
          <strong>Phone: </strong>
          (+61)<%= @user_profile.phone %>
        </p>

        <p>
          <strong>Address: </strong>
          <%= @user_profile.address %>
        </p>

        <%= link_to 'Edit Profile', edit_user_profile_path(@user_profile), class: "btn btn-primary mb-3" %>
         <%= link_to 'Make Booking', view_instructors_path, class: "btn btn-primary mb-3 ml-3" %>
      </div>
      <div class="col-4 border rounded">
        <p class=" h4 text-center mt-4">Children</p>
        <hr class="my-4">
        <% @students.each do |student| %>
        <% @booking = @bookings.where(student_id: student.id).last%>
          <p>
          <strong><%= "#{student.firstname} #{student.lastname}" %></strong>
          </p>
          <p class="lh-sm my-1">
          <strong>Age: </strong><%= ((Time.zone.now - student.dob.to_time) / 1.year.seconds).floor %>
          </p>
          <%if @booking.present? && @booking.date > Date.today-1%>
            <p class="lh-sm my-1">
            <strong>Next Booking: </strong> <%=link_to "#{@daytime.find(@timeslots.find(@booking.timeslot_id).daytime_id).time} - #{@booking.date.strftime("%d/%m/%Y")}", @booking %>
            </p>
          <%end%>
          <p class="lh-sm mt-1 mb-3">
          <strong>Skill Level: </strong>Skill Goes Here (WiP)
          </p>
          <%= link_to 'Edit', edit_student_path(student), class: "btn btn-primary btn-sm mr-1" %>
          <hr class="my-4">
        <%end%>
          <%= link_to 'Add Student', new_student_path, class: "btn btn-primary mb-3" %>
      </div>
  </div>
</div>
<div class="bg-light p-4 border rounded w-auto mx-5 mt-3 mb-3">
<p class="h1 text-center bg-light mx-auto">All Bookings !WIP!</p>
<hr class="my-2">
</div>